# ModelDock client join (Windows)
# This script installs Tailscale if missing and joins the ModelDock server's
# private network using a one-time auth key generated by the server owner.
#
# The auth key is a credential. It is single-use and short-lived: do not share it.
#
# Usage (the server owner fills in the values before sending this to the client):
#   powershell -ExecutionPolicy Bypass -File join-modeldock.ps1 -AuthKey "tskey-auth-..." -ChatUrl "https://server.taildomain.ts.net"

param(
  [Parameter(Mandatory = $true)][string]$AuthKey,
  [Parameter(Mandatory = $false)][string]$ChatUrl = "",
  [Parameter(Mandatory = $false)][string]$Hostname = $env:COMPUTERNAME
)

$ErrorActionPreference = "Stop"
$tailscaleExe = "C:\Program Files\Tailscale\tailscale.exe"

Write-Host "ModelDock - joining your team's private AI network..." -ForegroundColor Cyan

if (-not (Test-Path $tailscaleExe)) {
  Write-Host "Tailscale is not installed. Downloading the official installer..." -ForegroundColor Yellow
  $installer = Join-Path $env:TEMP "tailscale-setup.exe"
  Invoke-WebRequest -Uri "https://pkgs.tailscale.com/stable/tailscale-setup-latest.exe" -OutFile $installer
  Write-Host "Installing Tailscale (a UAC prompt may appear)..."
  Start-Process -FilePath $installer -ArgumentList "/quiet" -Wait
}

if (-not (Test-Path $tailscaleExe)) {
  throw "Tailscale did not install correctly. Open the Tailscale app once, then re-run this script."
}

Write-Host "Connecting this device to the network..."
& $tailscaleExe up --authkey $AuthKey --hostname $Hostname --accept-routes

Write-Host ""
Write-Host "Done. This device is now on your team's private network." -ForegroundColor Green
if ($ChatUrl -ne "") {
  Write-Host "Opening the chat: $ChatUrl"
  Start-Process $ChatUrl
} else {
  Write-Host "Ask the server owner for the chat address to start using ModelDock."
}
